package com.example.dataencryptionanddecryption;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
@SpringBootApplication
public class DataEncryptionAndDecryptionApplication {

    public static void main(String[] args) {
        SpringApplication.run(DataEncryptionAndDecryptionApplication.class, args);
    }

}
